import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import ReduxProvider from "@/redux/redux_provider";
import { Toaster } from "@/components/ui/sonner";
import { getMessages, setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import AuthProvider from "../../components/auth/authProvider";
import { notoSans, playfairDisplayHeading, tajawal } from "./fonts";
import { ScrollArea } from "@/components/ui/scroll-area";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);
  
  const messages = await getMessages();
  const direction = locale === "ar" ? "rtl" : "ltr";
   
 
  const activeFont = locale === "ar" ? tajawal.variable : notoSans.variable;

    
  return (
    <html
      lang={locale}
      dir={direction}
      className={cn(
        "h-full",
        "antialiased",
         activeFont ,
        playfairDisplayHeading.variable
      )}
    >
      <body className="font-sans overflow-hidden  antialiased bg-background text-foreground">
        <ScrollArea className="flex-1 h-full w-full" dir="rtl">

                 <NextIntlClientProvider locale={locale} messages={messages}>

          <ReduxProvider>
            <AuthProvider>
            {children}
            </AuthProvider>

           </ReduxProvider>
        </NextIntlClientProvider>

        <Toaster position="top-right" richColors />
        </ScrollArea>
 
      </body>
    </html>
  );
}